// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package admin

import (
	"context"
	"fmt"

	"github.com/gogf/gf/v2/frame/g"
)

func setTplAdmin(ctx context.Context, dir string, data g.Map) {

	d := g.Map{
		"mainTpl":   fmt.Sprintf("admin/%s/index.html", dir),
		"headTpl":   fmt.Sprintf("admin/%s/head.html", dir),
		"scriptTpl": fmt.Sprintf("admin/%s/script.html", dir),
		"path":      g.RequestFromCtx(ctx).Router.Uri,
	}
	for key, value := range data {
		d[key] = value
	}

	g.RequestFromCtx(ctx).Response.WriteTpl("admin/admin.html", d)
}
