// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gov2panel/internal/dao/internal"
)

// internalV2CouponDao is internal type for wrapping internal DAO implements.
type internalV2CouponDao = *internal.V2CouponDao

// v2CouponDao is the data access object for table v2_coupon.
// You can define custom methods on it to extend its functionality as you wish.
type v2CouponDao struct {
	internalV2CouponDao
}

var (
	// V2Coupon is globally public accessible object for table v2_coupon operations.
	V2Coupon = v2CouponDao{
		internal.NewV2CouponDao(),
	}
)

// Fill with you ideas below.
