// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gov2panel/internal/dao/internal"
)

// internalV2TicketMessageDao is internal type for wrapping internal DAO implements.
type internalV2TicketMessageDao = *internal.V2TicketMessageDao

// v2TicketMessageDao is the data access object for table v2_ticket_message.
// You can define custom methods on it to extend its functionality as you wish.
type v2TicketMessageDao struct {
	internalV2TicketMessageDao
}

var (
	// V2TicketMessage is globally public accessible object for table v2_ticket_message operations.
	V2TicketMessage = v2TicketMessageDao{
		internal.NewV2TicketMessageDao(),
	}
)

// Fill with you ideas below.
