// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gov2panel/internal/dao/internal"
)

// internalV2CouponUseDao is internal type for wrapping internal DAO implements.
type internalV2CouponUseDao = *internal.V2CouponUseDao

// v2CouponUseDao is the data access object for table v2_coupon_use.
// You can define custom methods on it to extend its functionality as you wish.
type v2CouponUseDao struct {
	internalV2CouponUseDao
}

var (
	// V2CouponUse is globally public accessible object for table v2_coupon_use operations.
	V2CouponUse = v2CouponUseDao{
		internal.NewV2CouponUseDao(),
	}
)

// Fill with you ideas below.
