// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gov2panel/internal/dao/internal"
)

// internalV2KnowledgeDao is internal type for wrapping internal DAO implements.
type internalV2KnowledgeDao = *internal.V2KnowledgeDao

// v2KnowledgeDao is the data access object for table v2_knowledge.
// You can define custom methods on it to extend its functionality as you wish.
type v2KnowledgeDao struct {
	internalV2KnowledgeDao
}

var (
	// V2Knowledge is globally public accessible object for table v2_knowledge operations.
	V2Knowledge = v2KnowledgeDao{
		internal.NewV2KnowledgeDao(),
	}
)

// Fill with you ideas below.
