// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gov2panel/internal/dao/internal"
)

// internalV2ProxyServiceDao is internal type for wrapping internal DAO implements.
type internalV2ProxyServiceDao = *internal.V2ProxyServiceDao

// v2ProxyServiceDao is the data access object for table v2_proxy_service.
// You can define custom methods on it to extend its functionality as you wish.
type v2ProxyServiceDao struct {
	internalV2ProxyServiceDao
}

var (
	// V2ProxyService is globally public accessible object for table v2_proxy_service operations.
	V2ProxyService = v2ProxyServiceDao{
		internal.NewV2ProxyServiceDao(),
	}
)

// Fill with you ideas below.
