// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gov2panel/internal/dao/internal"
)

// internalV2PlanDao is internal type for wrapping internal DAO implements.
type internalV2PlanDao = *internal.V2PlanDao

// v2PlanDao is the data access object for table v2_plan.
// You can define custom methods on it to extend its functionality as you wish.
type v2PlanDao struct {
	internalV2PlanDao
}

var (
	// V2Plan is globally public accessible object for table v2_plan operations.
	V2Plan = v2PlanDao{
		internal.NewV2PlanDao(),
	}
)

// Fill with you ideas below.
