// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"gov2panel/internal/dao/internal"
)

// v2ServiceRelayDao is the data access object for the table v2_service_relay.
// You can define custom methods on it to extend its functionality as needed.
type v2ServiceRelayDao struct {
	*internal.V2ServiceRelayDao
}

var (
	// V2ServiceRelay is a globally accessible object for table v2_service_relay operations.
	V2ServiceRelay = v2ServiceRelayDao{internal.NewV2ServiceRelayDao()}
)

// Add your custom methods and functionality below.
