// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gov2panel/internal/dao/internal"
)

// internalV2PaymentDao is internal type for wrapping internal DAO implements.
type internalV2PaymentDao = *internal.V2PaymentDao

// v2PaymentDao is the data access object for table v2_payment.
// You can define custom methods on it to extend its functionality as you wish.
type v2PaymentDao struct {
	internalV2PaymentDao
}

var (
	// V2Payment is globally public accessible object for table v2_payment operations.
	V2Payment = v2PaymentDao{
		internal.NewV2PaymentDao(),
	}
)

// Fill with you ideas below.
